import Head from "next/head";
import BarberServicesContainer from "@/components/admin/BarberServicesContainer";
import CustomerAppointmentsContainer from "@/components/admin/CustomerAppointmentsContainer";

export default function Home() {
  return (
    <>
      <Head>
        <title>OC FADES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full min-h-screen text-xs bg-neutral-500">
        <CustomerAppointmentsContainer />
        <BarberServicesContainer />
      </div>
    </>
  );
}
