import Head from "next/head";
import PageWrapper from "@/components/PageWrapper";
import Main from "@/components/Main";
import Calendar from "@/components/Calendar";
import Services from "@/components/Services";

export default function Home() {
  return (
    <>
      <Head>
        <title>OCF Barber</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageWrapper>
        <Main>
          <div className="p-8">
            <h2 className="font-medium mb-2">Create booking</h2>
            <h2 className="text-xs text-neutral-500 mb-4">
              Select a date and time that works for you
            </h2>
            <div className="mb-4">
              <Calendar currentDate={new Date()} />
            </div>
            <div className="">
              <Services />
            </div>
          </div>
        </Main>
      </PageWrapper>
    </>
  );
}
